### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mik-tf** [Mik-TF/flist_cli_v#1]
# TODO

- [x] print the url to the flist after running flist push
- [x] add ls function to show all flist
- [x] set sudo in front of docker if needed
- [ ] test on macos and windows, fix if needed

**Comment by mik-tf** [comment]
Will make the tests in another issue
